apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ${{ values.component_id }}-prod
  namespace: ${{values.application.split(":")[1]}}-build
  finalizers:
    - resources-finalizer.argocd.argoproj.io  
spec:
  project: default
  source:
    repoURL: https://github.com/raf-backstage-demo/${{values.application.split(":")[1]}}-gitops
    targetRevision: HEAD
    path: ./components/${{ values.component_id }}/chart
    helm:
      valueFiles:
        - ../value-files/values-prod.yaml
      values: | 
        quarkus-run: 
          image:
            tag: dummy
          baseDomain: ${{values.baseURL}}  
  destination:
    server: https://kubernetes.default.svc
    namespace: ${{values.application.split(":")[1]}}-prod
  syncPolicy:
    automated: 
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false
    - RespectIgnoreDifferences=true
    - ApplyOutOfSyncOnly=true    
    retry:
      backoff:
        duration: 5s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 10m # the maximum amount of time allowed for the backoff strategy
  ignoreDifferences:      
  - group: networking.istio.io
    kind: VirtualService
    name: ${{ values.component_id }}
    namespace: ${{values.application.split(":")[1]}}-prod
    jsonPointers:
    - /spec/hosts                   